### ISSUE TITLE
Link for DSharpPlus is broken and outdated

### ISSUE THREAD

**Issue by viveksh1** [DiscordAPI/libraries#35]
The current links for DSharpPlus no longer work as the repository was moved a while ago. Please change the URL from https://github.com/Naamloos/DSharpPlus to https://github.com/DSharpPlus/DSharpPlus. You can check the README of https://github.com/DSharpPlus/DSharpPlus for proof.

**Comment by Naamloos** [comment]
I'll fix it quickly

**Comment by Naamloos** [comment]
The url is already fixed. The web version hasn't reflected that change

**Comment by viveksh1** [comment]
> The url is already fixed. The web version hasn't reflected that change

Please fix the web version. That's what I'm talking about.

**Comment by Naamloos** [comment]
That's something I can't do myself. I'm sorry.

**Comment by viveksh1** [comment]
> That's something I can't do myself. I'm sorry.

It's okay, thanks for trying.
